### PR TITLE
Allow for a difference between iteration interval and transition interval

### PR DESCRIPTION
**Pull request by ghost**
Hey!

I realized that the iteration interval for the loop, as well as the transition interval were both being set by interval, that being the case, it means that the interval doesn't act as you would expect IE: you are not able to to control how long it sits on any one value, since the loop time and transition time are the same, its constantly changing.

This seems to be a good solution to allow more control.

### CODE REVIEW

**Comment by ghost** [comment]
Here is where I am using it, if you want to see my use case: https://lukehagar.com

**Comment by benzara-tahar** [comment]
Thanks @luke-hagar-sp for your contribution, I wasn't available last couple of weeks but I will get back at maintaining this. Will review your PR tomorrow.

**Comment by benzara-tahar** [comment]
I checked your PR, you're bringing practical and perhaps common usecase and it makes sense to delay each count animation a bit to result in a better transition.

However, I am starting to feel that the whole `interval` naming thing is just misleading (especially if we have two props (`transitionInterval ` and `interval`).
I suggest that we stick to the web standards and naming convensions

- `interval`: is the duration of each count iteration
- `transitionInterval ` is the delay between two count iterations

That being said, it would make perfect sense to call them (`delay` and `duration`) instead of (`transitionInterval ` and `interval`) respectively. It would be much easier to reason about it that way, just like css animations.

Please let me know if you can update your branch to accomodate with this. 
- rename `interval` to `duration`  ***I know it's a breaking change, but I think it's for the sake of a better api**
- rename `transitionInterval ` to `delay` 
- update the docs (README.md)

You can leave the demo page unchanged since I am working on updating all the dependecies and adding a single interactive sandbox using skeleton ui

image


Am also planning to some cleaning, adding some tests, setup github actions for automatic release of npm packages.. amoung other things.

**Comment by benzara-tahar** [comment]
Speaking about the api, `random `prop is difinitely off when we have something like `direction`!
I think I will remove it in favor of a new direction value.

```diff

	/**
 	 * counter direction, can be `up` or `down` defaults to `down`
	 */
-       export let direction: 'up' | 'down'  = 'down';	 
+	export let direction: 'up' | 'down' | 'random' = 'down';

-/**
-	 * setting to allow items in values to be displayed randomly
-	 */
-	export let random = false;
```

and if we can offer more flexibiliy we can do even this

```ts
export type CountValue = string|number;
export let direction: 'up' | 'down' | 'random' | ((current: CountValue, values: CountValue[]) => CountValue);
```
This means you can have your own logic and not just up,down or random.

btw, you don't have to worry about that for this PR

**Comment by ghost** [comment]
Hey Benzara,

I agree here on all this completely, I'm working on implementing the ideas, but I am struggling with some CSS issues here, I have gone around in circles trying to fix this.

Do you see how the top of the numbers on the right seem to be cut off? its just a little bit there, but its really bothering me, also for the top of the section here, it seems that its actually riding a little high inside the box, later when its close to the bottom, it seems to be a little low then as well, I feel like we are a little off with the calc for top.
Screen Shot 2022-12-30 at 2 04 21 PM
Screen Shot 2022-12-30 at 2 04 04 PM

I would love your thoughts here.

**Comment by benzara-tahar** [comment]
@luke-hagar-sp  I wasn't able to reproduce that on my end, what OS/Browser you're using (am on windows/chrome), berhaps that's related to how new line is interepreted  (`\n` `\r` `\n\r` `\r\n`) ?

**Comment by ghost** [comment]
Hey @benzara-tahar, 
This is on vivaldi on Mac

**Comment by ghost** [comment]
I went ahead and implemented the basics of what we discussed, I'll leave the rest for you to handle.

I'm loving the component!

**Comment by benzara-tahar** [comment]
Thanks @luke-hagar-sp , am glad you're liking this small component, I'll merge your work and add to it the few changes I've been working on.

**Pull request merged**
